spring:
  application:
    name: shipment-service      # config 서버에서 이 이름으로 파일 조회
  config:
    import: "configserver:"      # Config Server에서 설정 가져옴
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        max-attempts: 3
        initial-interval: 1000
